function gratd3(X1, Y1, Z1)
%CREATEFIGURE(X1, Y1, Z1)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Z1:  vector of z data

%  Auto-generated by MATLAB on 10-Nov-2018 21:13:21

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot3
stem3(X1,Y1,Z1,'LineWidth',3,'Color',[1 0 0]);

% Create zlabel
zlabel('Parte Imaginaria de f[n]','FontName','Century Gothic');

% Create ylabel
ylabel('Parte real f[n]','FontName','Century Gothic');

% Create xlabel
xlabel('n','FontName','Century Gothic');

% Create title
title('Grafica de Señales Dicretas');

view(axes1,[-37.5 30]);
box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'Color',[0.729411780834198 0.831372559070587 0.95686274766922],...
    'FontName','Century Gothic','XColor',[0 0 1],'YColor',[0 0 1],'ZColor',...
    [0 0 1]);
