function gratdd3(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 11-Nov-2018 01:04:18

% Create figure
figure1 = figure('Color',...
    [0.972549021244049 0.972549021244049 0.972549021244049]);
colormap(gray);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
stem(X1,Y1);

% Create ylabel
ylabel('u(n)');

% Create xlabel
xlabel('n');

% Create title
title('Gráfica de Señales Discretas');

box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'Color',[0.729411780834198 0.831372559070587 0.95686274766922],...
    'FontName','Century Gothic','XAxisLocation','origin','XColor',[0 0 1],...
    'YAxisLocation','origin','YColor',[0 0 1],'ZColor',[0 0 1]);
